# https://github.com/googleapis/repo-automation-bots/tree/main/packages/release-please#configuration
handleGHRelease: true
releaseType: simple
changelogPath: jellyfin-server/CHANGELOG.md
extraFiles:
  - path: jellyfin-server/config.yaml
    type: yaml
    jsonpath: $.version
  - path: jellyfin-server-hn/config.yaml
    type: yaml
    jsonpath: $.version
